[_]
schema-version = "0.2"

# ── Buildpack configuration ──────────────────────────────
[[io.buildpacks.build.env]]
name  = "BP_NODE_VERSION"
value = "20.*"

[[io.buildpacks.build.env]]
name  = "BP_NODE_RUN_SCRIPTS"
value = "build"

[[io.buildpacks.build.env]]
name  = "BP_WEB_SERVER"
value = "nginx"

[[io.buildpacks.build.env]]
name  = "BP_WEB_SERVER_ROOT"
value = "dist"

[[io.buildpacks.build.env]]
name  = "BP_NGINX_CONF_LOCATION"
value = "./nginx.conf"

[io.buildpacks]
  [[io.buildpacks.group]]
  uri = "paketo-buildpacks/web-servers"

  [io.buildpacks.build]
  exclude = ["node_modules/", "*.md", ".git/", ".vscode/", ".env"]
