# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class BPMNEdge(BaseModel):
    source_id: typing.Optional[str] = Field(default=None, description='The id of the source BPMNNode.')
    target_id: typing.Optional[str] = Field(default=None, description='The id of the target BPMNNode.')
    condition_expression: typing.Optional[str] = Field(default=None, description='For edges leaving an ExclusiveGateway, the boolean condition that activates this path. Null for unconditional flows.')

class BPMNInterviewState(BaseModel):
    nodes: typing.List["BPMNNode"] = Field(description='The full list of BPMN nodes in the current graph. Updated cumulatively on each turn.')
    edges: typing.List["BPMNEdge"] = Field(description='The full list of edges connecting nodes. Updated cumulatively on each turn.')
    unresolved_paths: typing.List[str] = Field(description='Human-readable descriptions of dead-end paths, missing connections, or ambiguities that need user input to resolve. E.g. \'Gateway gw_1 has no outgoing edge for the FALSE branch.\'')
    is_ready_to_compile: typing.Optional[bool] = Field(default=None, description='True ONLY when: (1) there are zero unresolved_paths, (2) every ServiceTask has ontology_class and data_source filled, (3) the user has explicitly confirmed the workflow is complete. Default to false.')
    agent_reply: typing.Optional[str] = Field(default=None, description='Natural language response to the user. This is the conversational text shown in the Neural Stream.')

class BPMNNode(BaseModel):
    id: typing.Optional[str] = Field(default=None, description='Unique identifier for this node, e.g. \'task_1\', \'gw_1\', \'timer_1\'.')
    name: typing.Optional[str] = Field(default=None, description='Human-readable label for this node, e.g. \'Ingest Engine Telemetry\'.')
    node_type: typing.Optional[types.BPMNNodeType] = Field(default=None, description='The BPMN element type.')
    ontology_class: typing.Optional[str] = Field(default=None, description='IOF-MRO / MIMOSA ontology URI grounding this node. REQUIRED for ServiceTask, null for others. Must come from the available_ontology_classes list.')
    data_source: typing.Optional[str] = Field(default=None, description='DataHub / dbt model name grounding this node. REQUIRED for ServiceTask, null for others. Must come from the available_data_sources list.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
