# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class BPMNNodeType(str, Enum):
    ServiceTask = "ServiceTask"
    UserTask = "UserTask"
    ExclusiveGateway = "ExclusiveGateway"
    TimerEvent = "TimerEvent"

# #########################################################################
# Generated classes (3)
# #########################################################################

class BPMNEdge(BaseModel):
    source_id: str = Field(description='The id of the source BPMNNode.')
    target_id: str = Field(description='The id of the target BPMNNode.')
    condition_expression: typing.Optional[str] = Field(default=None, description='For edges leaving an ExclusiveGateway, the boolean condition that activates this path. Null for unconditional flows.')

class BPMNInterviewState(BaseModel):
    nodes: typing.List["BPMNNode"] = Field(description='The full list of BPMN nodes in the current graph. Updated cumulatively on each turn.')
    edges: typing.List["BPMNEdge"] = Field(description='The full list of edges connecting nodes. Updated cumulatively on each turn.')
    unresolved_paths: typing.List[str] = Field(description='Human-readable descriptions of dead-end paths, missing connections, or ambiguities that need user input to resolve. E.g. \'Gateway gw_1 has no outgoing edge for the FALSE branch.\'')
    is_ready_to_compile: bool = Field(description='True ONLY when: (1) there are zero unresolved_paths, (2) every ServiceTask has ontology_class and data_source filled, (3) the user has explicitly confirmed the workflow is complete. Default to false.')
    agent_reply: str = Field(description='Natural language response to the user. This is the conversational text shown in the Neural Stream.')

class BPMNNode(BaseModel):
    id: str = Field(description='Unique identifier for this node, e.g. \'task_1\', \'gw_1\', \'timer_1\'.')
    name: str = Field(description='Human-readable label for this node, e.g. \'Ingest Engine Telemetry\'.')
    node_type: BPMNNodeType = Field(description='The BPMN element type.')
    ontology_class: typing.Optional[str] = Field(default=None, description='IOF-MRO / MIMOSA ontology URI grounding this node. REQUIRED for ServiceTask, null for others. Must come from the available_ontology_classes list.')
    data_source: typing.Optional[str] = Field(default=None, description='DataHub / dbt model name grounding this node. REQUIRED for ServiceTask, null for others. Must come from the available_data_sources list.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
