# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.BPMNEdge": types.BPMNEdge,
    "stream_types.BPMNEdge": stream_types.BPMNEdge,

    "types.BPMNInterviewState": types.BPMNInterviewState,
    "stream_types.BPMNInterviewState": stream_types.BPMNInterviewState,

    "types.BPMNNode": types.BPMNNode,
    "stream_types.BPMNNode": stream_types.BPMNNode,


    "types.BPMNNodeType": types.BPMNNodeType,

}